spring:
  application:
       name: friend-finder

  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/orclpdb
    username: hr
    password: hr
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  messages:
    baseName: i18n/messages
    local-default: en

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 101MB


spring-token:
  secret: kkkjgkhkd669$#65@#fghdfyhrtyerytryrtydfgjfg
  time: 1h



server:
  port: 9090